# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# Run locally with: goreleaser --snapshot --skip-publish --rm-dist
project_name: kvs
before:
  hooks:
    - go mod tidy
builds:
- binary: '{{ .ProjectName }}'
  env:
    - CGO_ENABLED=0
  ldflags:
    - -a -extldflags "-static"
  goos:
      - windows
      - linux
      - darwin
  goarch:
      - amd64
archives:
- replacements:
    darwin: macOS
    windows: win
    amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .ProjectName }}_{{ .Tag }}"
nfpms:
  -
    package_name: kv
    vendor: Luca Sepe
    homepage: https://lucasepe.it/
    maintainer: Luca Sepe <luca.sepe@gmail.com>
    description: Minimal persistent key-value store.
    license: MIT
    replacements:
      amd64: 64-bit
    formats:
      - deb
      - rpm
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
